preprocessing:
  convert_h5: true

reconstructions:
  no_gating: true
  hard_gating: true
  soft_gating: true
  xdgrasp: true
  imoco: true
  mocostorm: true

device:
  gpu: true

output:
  img_shape: [256, 256, 256]