preprocessing:
  convert_h5: false

reconstructions:
  no_gating: true
  hard_gating: true
  soft_gating: true
  xdgrasp: true
  imoco: true
  mocostorm: true

hard_gating:
  thresh: 50

soft_gating:
  thresh: 20
  gating_weight: 0.8

device:
  gpu: true

output:
  img_shape: [256, 256, 256]